### ISSUE TITLE
Incorrect (?) handling of include path options.

### ISSUE THREAD

**Issue by nikitadanilov** [CastXML/CastXML#183] opened 2020-09-12 16:09 UTC
```
$ cat dir/a.c
#include "dir/b.h"
$ cat dir/b.h
#define X 1
$ castxml -I. dir/a.c
dir/a.c:1:10: fatal error: cannot open file 'dir/dir/b.h': No such file or
      directory
#include "dir/b.h"
         ^
1 error generated.
```
castxml cannot find ./dir/b.h and tries to open dir/dir/b.h. Presumably, this happens because the file is specified on the command line as dir/a.c and "dir/" is prefixed to all include paths.

clang works correctly:
```
$ clang -E -I. dir/a.c
# 1 "dir/a.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 331 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "dir/a.c" 2
# 1 "./dir/b.h" 1
# 2 "dir/a.c" 2
$ castxml -v
clang version 10.0.1 
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: 
```

**Comment by bradking** [comment] 2020-09-14 13:39
I cannot reproduce this.  The described example works fine for me.

* On what platform are you running `castxml`?
* What is `castxml --version`?
* What is `castxml -I. dir/a.c -v`?
* What is `castxml -I. dir/a.c -###`?

**Comment by nikitadanilov** [comment] 2020-09-14 17:11
This is castxml installed on macos by `brew install castxml`.
```
$ castxml --version
castxml version 0.3.3

CastXML project maintained and supported by Kitware (kitware.com).

clang version 10.0.0 (https://github.com/CastXML/CastXMLSuperbuild 599fcf88b0e95a58c19a47958339d183ce6afa72)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: 
$ castxml -I. dir/a.c -v
clang version 10.0.0 (https://github.com/CastXML/CastXMLSuperbuild 599fcf88b0e95a58c19a47958339d183ce6afa72)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: 
clang -cc1 version 10.0.0 based upon LLVM 10.0.0 default target x86_64-apple-darwin16.7.0
#include "..." search starts here:
#include <...> search starts here:
 .
 /usr/local/include
 /Users/nikita/bin/castxml/share/castxml/clang/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
$ castxml -I. dir/a.c -###
clang version 10.0.0 (https://github.com/CastXML/CastXMLSuperbuild 599fcf88b0e95a58c19a47958339d183ce6afa72)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: 
 "clang" "-cc1" "-triple" "x86_64-apple-macosx10.12.0" "-Wdeprecated-objc-isa-usage" "-Werror=deprecated-objc-isa-usage" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "a.c" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-mframe-pointer=all" "-fno-rounding-math" "-masm-verbose" "-munwind-tables" "-faligned-alloc-unavailable" "-target-cpu" "penryn" "-dwarf-column-info" "-debugger-tuning=lldb" "-target-linker-version" "530" "-resource-dir" "/Users/nikita/bin/castxml/share/castxml/clang" "-I" "." "-internal-isystem" "/usr/local/include" "-internal-isystem" "/Users/nikita/bin/castxml/share/castxml/clang/include" "-internal-externc-isystem" "/usr/include" "-fdebug-compilation-dir" "/tmp" "-ferror-limit" "19" "-fmessage-length" "82" "-stack-protector" "1" "-fblocks" "-fencode-extended-block-signature" "-fregister-global-dtors-with-atexit" "-fgnuc-version=4.2.1" "-fobjc-runtime=macosx-10.12.0" "-fmax-type-align=16" "-fdiagnostics-show-option" "-x" "c" "dir/a.c"
```
I just checked with the castxml binary from kitware.com and it works correctly:
```
$ ~/bin/castxml/bin/castxml --version
castxml version 0.3.3

CastXML project maintained and supported by Kitware (kitware.com).

clang version 10.0.0 (https://github.com/CastXML/CastXMLSuperbuild 599fcf88b0e95a58c19a47958339d183ce6afa72)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: 
$ ~/bin/castxml/bin/castxml -I. dir/a.c
$
```

**Comment by bradking** [comment] 2020-09-14 17:12
Thanks.  I suspect this is the same problem as #176.  I'll close this issue in favor of that one.

**Closed by bradking** 2020-09-14 17:12 UTC
