### ISSUE TITLE
Errors when compiling on Windows

### ISSUE THREAD

**Issue by andrasfuchs** [CastXML/CastXML#83] opened 2017-01-04 05:50 UTC
I couldn't find LLVM/Clang SDK (mentioned in https://github.com/CastXML/CastXML/blob/master/README.rst), is it still available somewhere?

After getting LLVM from http://llvm.org/svn/llvm-project/llvm/trunk and clang http://llvm.org/svn/llvm-project/cfe/trunk it is still not possible to build CastXML with cmake on Windows.

First error came when I realized that there is no /share/llvm/cmake directory in the llvm. So I got the following error:
> By not providing "FindLLVM.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "LLVM", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "LLVM" with any of
>   the following names:
> 
>     LLVMConfig.cmake
>     llvm-config.cmake

After setting that the only directory which contains llvm-config.cmake, /cmake/modules, I passed that, and I got the following:
> Please set CLANG_RESOURCE_DIR to the Clang SDK directory containing
>   "include/stddef.h", typically of the form "<prefix>/lib/clang/0.0.0".
> 

Then, after setting it to the  /tools/clang/lib/headers directory, I finally got this:
> CMake Error at C:/Work/llvm/cmake/modules/LLVM-Config.cmake:203 (message):
>   Library `option' not found in list of llvm libraries.
> Call Stack (most recent call first):
>   src/CMakeLists.txt:46 (llvm_map_components_to_libnames)

**Comment by bradking** [comment] 2017-01-09 14:50
The `LLVM_DIR` must be set to  `<prefix>/lib/cmake/llvm`, where `<prefix>` is the installation tree prefix of LLVM/Clang.  Unfortunately LLVM provides a file called `LLVM-Config.cmake` that has nothing to do with the files CMake is looking for, and is in a different directory.

**Comment by andrasfuchs** [comment] 2017-01-10 12:39
Neither LLVM, nor Clang has a cmake directory in their lib dir. I must have the wrong source. 
Could you tell me where could I get LLVM/Clang?

**Comment by bradking** [comment] 2017-01-10 13:32
Clone LLVM and Clang from source and configure a build and install tree using CMake.  See the upstream [instructions](http://clang.llvm.org/get_started.html).

**Comment by bradking** [comment] 2017-01-12 21:34
Closing as this is not a bug.  Discussion of getting it to build can still continue in the closed issue if needed.

**Closed by bradking** 2017-01-12 21:34 UTC

**Comment by andrasfuchs** [comment] 2017-01-13 04:23
Hi Brad, I checked all the 5 SVN repositories for the /lib/cmake/llvm folder, but none of them has it. Are the instructions you linked up-to-date?

These were the repos I checked:
http://llvm.org/svn/llvm-project/llvm/trunk
http://llvm.org/svn/llvm-project/cfe/trunk
http://llvm.org/svn/llvm-project/clang-tools-extra/trunk (optional)
http://llvm.org/svn/llvm-project/compiler-rt/trunk (optional)
http://llvm.org/svn/llvm-project/libcxx/trunk (optional)

**Comment by bradking** [comment] 2017-01-13 12:51
@andrasfuchs you're supposed to build LLVM/Clang from source and install it.  Then the file appears in the installation tree.  The instructions I linked match the URLs you posted:

```console
$ svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm
$ cd llvm/tools
$ svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
$ cd ../..
...
```

**Comment by bradking** [comment] 2018-07-25 14:15
See additional documentation on [Building LLVM with CMake](http://llvm.org/docs/CMake.html).

**Comment by zjd1988** [comment] 2018-07-26 00:12
@bradking Thank you，i will try this later。Now i found a INSTALL.vcxproj，and build it 。Finally it worked，i found llvm/clang is installed in "C:\Program Files (x86)\LLVM\lib\cmake",Anyway,thank you again.
