### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by andrasfuchs** [CastXML/CastXML#82] opened 2017-01-04 04:20 UTC
Could you create releases periodically and publish them here on the Releases tab? (https://github.com/CastXML/CastXML/releases)

I'm trying to compile it on Windows to replace gcc-xml, but I constantly hitting a wall. I will probably be able to build it eventually, but it would spare a lot of time for others, if there were compiled binaries available to download.

**Comment by iMichka** [comment] 2017-01-04 07:09
I wrote a small summary for my project on how to install castxml: http://pygccxml.readthedocs.io/en/develop/install.html#prerequisite-castxml

The binaries are the one we use for ITK. But it would be maybe better if we had an automatic build infrastructure on this repo to build the binaries on the fly.

**Comment by andrasfuchs** [comment] 2017-01-04 07:55
This is great! Thanks a lot for the binaries!

As I can see [here](http://public.kitware.com/pipermail/castxml/2015-July/000014.html), CastXML not 100% drop-in replacement of gcc-xml and I got a few errors after generating ActiViz with cmake and with the castxml.exe defined as gccxml.exe, but I think I'm a step closed to the goal.

All the errors are related to --gccxml-compiler, -fxml and -fxml-start arguments, so I hope that replacing them with the CastXML's argument names will fix the them all.

**Comment by iMichka** [comment] 2017-01-04 17:05
Yes, you are right, CastXML is not a 100% drop-in replacement. What I wanted to say is that the xml files produced are really similar (we tried to not break the API), but you still will need to adapt the CastXML flags to make it work.

**Comment by acmill0905** [comment] 2018-02-21 14:26
Hi andrasfuchs

I'm also trying to build Activiz.NET and came across the gccxml issue. 

Just wondering if you managed to solve it in the end, and if so do you have any tips for getting it to work with CastXML?

Many thank!

**Comment by andrasfuchs** [comment] 2018-02-22 10:45
Hi @acmill0905,

I don't remember if this was the exact point when I decided not to pursue Activiz.NET, but I finally gave up.

Sorry I couldn't help!

**Comment by acmill0905** [comment] 2018-02-22 11:00
Hi @andrasfuchs ,

Thanks for letting me know. I contacted Activiz support and they confirmed there are currently no up to date instructions for compilation, so looks like at present if anyone needs to distribute it, purchasing the commercial license for a one-off fee of 1800€ could be the only option.

Cheers!

**Comment by gerddie** [comment] 2018-11-25 21:35
I asked for this before, I now that this package FTBFS in Debian because the version there doesn't support llvm-7.9 which apparently is already fixed in the tree, I like to ask this  again: Would you please be so kind as to tag releases, because then I could see in my  [Debian watch list](https://qa.debian.org/developer.php?login=gw.fossdev@gmail.com)  - rightmost column, that an update is available, and thanks to  the tooling in Debian I could properly get the latest release tarball and woudn't have to pull the latest changes from git, invent a version tag, and then manually create a tarball with this version. It would also help tracking bugs if you as upstream would provide a proper reverence by adding a tag once in a while, e.g. when bugs with a new version of gcc or llvm were fixed. In summary, *tagging* releases would *really* be helpful, and if you think the software is not stable, then, by all means, tag is as beta or alpha, but *please* put some tags on it that can be tracked, for you it's just two git commands away, but for us packagers it would go a long way.  Thank you very much for your consideration.

**Comment by scpeters** [comment] 2019-03-30 18:37
@bradking thanks for your work in developing and maintaining this project, but without official releases and tags, this doesn't meet the criteria for [Acceptable Formulae in homebrew](https://docs.brew.sh/Acceptable-Formulae#stable-versions), which makes it subject to removal from homebrew-core

* https://github.com/Homebrew/homebrew-core/pull/38537#issuecomment-478271922

**Comment by TheChymera** [comment] 2019-04-01 00:30
I too would encourage you to start doing releases, as it makes the unambiguous identification of code versions more succinct. For the time being, however, Gentoo Linux provides all the required features for us to work around this. Commit 6b3d3f985f4607430d0e7ecd835ee80b29f3ae96 is known as [pre-release 9 of version 0.0.0 (`0.0.0_pre9`)](https://gitweb.gentoo.org/proj/sci.git/tree/dev-cpp/castxml/castxml-0.0.0_pre9.ebuild?id=270ef898ea12e14ab878feacc587ba4bed3cc6f7) on Gentoo.

**Comment by bradking** [comment] 2019-04-18 14:03
#140 updated the version scheme to document and provide a clear version number for both release and development versions.  That way either can be packaged at any time.

**Comment by bradking** [comment] 2019-04-18 14:04
I've published a [0.2.0 release](https://github.com/CastXML/CastXML/releases/tag/v0.2.0).

**Comment by scpeters** [comment] 2019-04-18 19:25
Thanks!

**Comment by scpeters** [comment] 2019-04-18 19:31
Using this new release in homebrew https://github.com/Homebrew/homebrew-core/pull/39052

**Comment by TheChymera** [comment] 2019-04-20 17:15
Version [`0.2.0`](https://gitweb.gentoo.org/proj/sci.git/commit/?id=1479fefbd0bfef1a5154474d0e5acf6239bf8579) released for Gentoo. Thanks!

**Closed** 2019-06-22 11:31 UTC
