### ISSUE TITLE
va_list arguments not printed correctly but as "?unknown?"

### ISSUE THREAD

**Issue by teto** [CastXML/CastXML#66] opened 2016-07-24 17:12 UTC
When printing declaration that contains a va_list as argument, pygccxml prints  "?unknown?" instead. 

For instance when parsing "int vasprintf(char **strp, const char *fmt, va_list ap);"  will generate:
int dce_vasprintf ( char * *, char const *,?unknown? *);

**Comment by teto** [comment] 2016-07-24 19:20
Here is a result  of  an analysis
https://transfer.sh/Jaqfy/test.h.xml

va_list is seen as a Typedef to "__va_list_tag".

**Comment by iMichka** [comment] 2016-07-24 21:55
We had a problem when we moved to castxml: there were a lot of "__va_list_tag" declarations "polluting" the declaration tree. As I was in a hurry to get the "standard" parsing up and running (with pyplusplus), I just disabled that declaration.

Could you please try by passing the f1 flag like explained here:
https://github.com/gccxml/pygccxml/blob/715361fed6ca7440c2ccbac9e77ac6407769c21a/CHANGELOG.md#version-171

It will also enable more internal stuff: https://github.com/gccxml/pygccxml/blob/25bf2b2035dba7c6b75f2a6483f542be468e2956/pygccxml/parser/scanner.py#L210-L218

I never thought it may be a problem, maybe I need to define a better way to handle that case. I never wrote a detailed help/documentation section about that because I never thought it would be a problem one day.

Hope that helps.

**Comment by teto** [comment] 2016-07-25 15:11
If I enabled it via : 
```
        xml_generator_config = parser.xml_generator_configuration_t(
            xml_generator_path=generator_path,
            xml_generator=generator_name,
            flags= ["f1"])
```
which is converted by pygccxml into a `__va_list_tag *` argument (and then generates `error: ‘__va_list_tag’ has not been declared` so I guess pygccxml ought to print it as "va_list").

For now, if the  argument starts with "?unknown?", I convert it to va_list and it seems to work but that's a workaround I guess

**Comment by bradking** [comment] 2016-08-01 13:25
@iMichka is this a CastXML issue or a pygccxml issue?

**Comment by iMichka** [comment] 2016-08-06 11:35
@bradking I had no time to look at this. I'm on holidays, and will come back in 2 weeks, so I will only have internet from time to time. The ```unknown``` comes from pygccxml, so it is probably a pygcxml problem. https://github.com/gccxml/pygccxml/blob/10829aa6bf6d06df6d6a6cf34af5544e31ddcfa2/pygccxml/declarations/cpptypes.py#L122

This issue would be better moved to the pygccxml issue tracker. I will re-open a new issue here if the problem is coming from castxml.

**Comment by bradking** [comment] 2016-08-16 13:47
Closing for now as this appears to be a pygccxml issue and not a CastXML one.

**Closed by bradking** 2016-08-16 13:47 UTC
